# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Kwota'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='item',
            field=models.CharField(max_length=200, verbose_name='Nazwa'),
        ),
    ]
