# Generated by Django 4.2.8 on 2024-02-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_auto_20171128_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='income',
            name='item',
            field=models.CharField(max_length=200, verbose_name='item'),
        ),
    ]
